### ISSUE TITLE
Conflit entre les noms de lieux similaire

### ISSUE THREAD

**Issue by OursBlanc42** [zigotteau/donjon#31]
**Exemple code donjon :**

`PARTIE "Introduction".
avant commencer le jeu:
  changer le joueur se trouve dans l'appartement.

-- APPARTEMENT
L'appartement est un lieu à l'intérieur de Paris.
Sa description est "Description de l'appartement".
Interpréter chambre comme appartement.

-- Paris
Paris est un lieu.
Sa description est "Description de Paris".

-- Paris Match
Paris Match est un lieu à l'intérieur de Paris.
Sa description est "Description du Paris Match".

avant aller vers Paris, aller vers Paris Match, ou aller vers l'appartement :
  dire "{/Vous partez de [intitulé ici] pour vour rendre vers [intitulé ceci]./}{n}";
  changer le joueur se trouve dans ceci;
  dire "{n}{_{*[titre ici]*}_}";
  dire "{n}[description ici][contenu ici]";
  stopper l’action.`

**Conflit entre Paris et Paris Match. Voilà ce ça donne ingame :**  

`(jeu sans titre)

Un jeu de (anonyme)

L'appartement
Description de l'appartement

Sorties :
- sortir (so) − ?

> sortir (aller dehors)
Paris
Description du Paris Match

Sorties :
- entrer (en) − L'appartement
- entrer (en) − Paris
- sortir (so) − Paris

> aller vers Paris
Vous partez de Paris pour vour rendre vers Paris.

Paris
Description du Paris Match`

**Comment by zigotteau** [comment]
Probalement que cela se produit lors de l'analyse du scénario: il faudrait tenir compte de l'épithète si ce n'est pas déjà fait.

**Comment by zigotteau** [comment]
C’est résolu avec la version 0.110.

![image](https://user-images.githubusercontent.com/28443944/108594169-9e0f3a80-7378-11eb-8020-61b89c418345.png)

![image](https://user-images.githubusercontent.com/28443944/108594234-065e1c00-7379-11eb-8d6f-0ee04d198d9e.png)

À présent lors de l’analyse de la description du monde, lorsque des éléments sont décrits relativement à d’autres :
- Il tient toujours compte de l’épithète.
- Il ne tient plus compte des majuscules.
