### ISSUE TITLE
Texte dynamique : condition historique contient ne fonctionne pas

### ISSUE THREAD

**Issue by OursBlanc42** [zigotteau/donjon#32]
Le code suivant ne fonctionne pas : 

`-- La marchande
La marchande est une femme sur la place.
Son info est "La marchande de potions [si l'historique contient "guilde des voleurs"] on m'a dit qu'elle vend secrétement des poisons...[sinon] elle propose tout un tas de fiole aux couleurs vives.[fin si]".`

info est lié à la commande personnalisé "penser".

penser à marchande est censé afficher son info, + texte conditionnel.
Or, j'ai que la partie "la marchande de potions" et rien aprés; (que l'historique contient "guilde des voleurs" ou pas)

**Comment by zigotteau** [comment]
![image](https://user-images.githubusercontent.com/28443944/105739340-4b3c9180-5f38-11eb-8292-4dc1f3a307db.png)

Il y a un souci lors de l'analyse du scénario. probablement à cause des " " à l'intérieur d'une Texte.

**Comment by zigotteau** [comment]
avec la mise à jour 0.105 il y a aura une solution qui consite à ne pas mettre de guillemets si la condition est dans un texte 👍 

![image](https://user-images.githubusercontent.com/28443944/105741550-b71ff980-5f3a-11eb-8f1a-7cc4bcf6ae21.png)
