### ISSUE TITLE
Ajouter des typos différentes

### ISSUE THREAD

**Issue by OursBlanc42** [zigotteau/donjon#37]
Une fonctionnalité qui pourrait être sympa à mettre en place en plus des {+couleur+} et autre {/italique/} ca serait de pouvoir choisir une typo.

Typo "neutre" (arial sans serrif and cie)
Typo "manuscrite" (une cursive)
Typo "typewriter" (effet machine à écrire)
Typo "gothique" (effet médiéval)

avec un code spécifique à chaque typo {1 {2 {3 {4 ?        {&   {é   {"   {'   ?

**Comment by zigotteau** [comment]
![image](https://user-images.githubusercontent.com/28443944/106363156-288aee00-6327-11eb-9b6b-573b74a11622.png)
