### ISSUE TITLE
Les synonymes (via interpréter) ne sont pas pris en compte dans "Sa réaction concernant BIDULE est "

### ISSUE THREAD

**Issue by OursBlanc42** [zigotteau/donjon#38]

**Comment by zigotteau** [comment]
Hello,

À priori, c'est sensé fonctionner.
Je viens de tester en mettant un synonyme à la lettre dans sauvons_noel et ça a fonctionné.

Du coup tu as du trouver un cas plus particulier qui bogue.
Il s'agissait d'un objet ou d'un lieu ? Avec un nom simple ou composé ? Avec une majuscule ?

![image](https://user-images.githubusercontent.com/28443944/105916561-63dca280-6031-11eb-955d-000e1027c214.png)

![image](https://user-images.githubusercontent.com/28443944/105916356-0e07fa80-6031-11eb-9570-9bf4a8536ba4.png)

**Comment by zigotteau** [comment]
Les synonymes fonctionnent pour les réactions mais seulement durant le jeu.
Cela signifie qu’il faut utiliser le vrai nom de l’objet et non le synonyme lorsqu’on écrit le scénario du jeu :

![souci_synonymes](https://user-images.githubusercontent.com/28443944/106360305-0342b380-6318-11eb-9f61-5c434b39def5.png)
