### ISSUE TITLE
Bug: jeu se termine sans remplir les conditions pour "terminer le jeu"

### ISSUE THREAD

**Issue by krisdoc** [zigotteau/donjon#51]
Problème constaté le 15/08 (fonctionnait très bien le 14). 
Utilisation de l'éditeur en ligne.
**Description**: 
_Contexte_: plusieurs personnages sont décrits avec leurs diverses réactions. Certains personnages, lorsqu'un compteur atteint une certaine valeur (7), déclenchent une action avec choix (accepter/refuser demande en mariage). Si c'est accepter, cela met fin au jeu.
_Problème_: après 2 intéractions avec un pnj mariable, le jeu se termine sans explications. La valeur seuil n'est pas atteinte.
_Message d'erreur_: "Le jeu est terminé.
Pour débuter une nouvelle partie veuillez actualiser la page web." A tout hasard, je joins le fichier du jeu au format texte (je ne peux pas joindre un fichier .djn).

PS: je suis nouvelle sur github, j'espère que c'est la bonne procédure pour signaler un problème.
[terrencehall.djn.txt](https://github.com/zigotteau/donjon/files/6987770/terrencehall.djn.txt)

**Comment by zigotteau** [comment]
Bonjour Kris,

Dans la condition 
```
si xxxxx atteint 7,
  dire "...";
  terminer le jeu.
```
 Tu dois terminer ta condition par deux points (` : `) pour pouvoir la suivre de plusieurs conséquences puis un `fin si` suivi ici du point final.

En effet, la virgule (` , `) permet de réaliser une condition rapide avec une seule conséquence maximum et le `fin si` n'est alors pas nécessaire.

https://donjon.fi/wiki/creer/conditions/ponctuation/regle_ou_action

PS: Je n'ai pas oublié ta demande de réaliser un tuto sur les conditions, c'est le prochain qui sort 😉

**Comment by krisdoc** [comment]
Merci beaucoup pour ton aide! J'ai pu corriger le problème.
