### ISSUE TITLE
supports: ne pas décrire les objets dessus lors de la description du lieu (paramètre)

### ISSUE THREAD

**Issue by zigotteau** [zigotteau/donjon#72]
Ajouter un paramètre qui permet de désactiver l’énumération des objets posés sur les supports lors de la description d’un lieu.

**Comment by Valkann** [comment]
J'ai l'impression que le mot cléf caché n'est plus pris en compte

> Un réveil difficile 0.01
> 
> Un jeu de Aymeric Besset
> 
> Licence : [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)
> 
> Salle 01
> Une grande salle avec des caissons à examiner
> Il n’y a pas de sortie.
> 
> > ex caisson (examiner caisson)
> D'autres caissons d'hypersommeil semblent cassés, leurs occupants morts, et d'autres encore semblent déjà ouvert et vide. Un corps semble différent. Votre caisson porte le numéro 13.
> 
> > ex corps (examiner corps)
> Un corps est différent, il est par terre et ne semble pas être un occupant des caissons.
> Dessus, il y a un uniforme.
> 
> > deb uniforme (déboguer uniforme)
> 1 élément trouvé :
> 
> • l’uniforme (m, s)
> type
> objet → élément → intitulé
> ID
> 21
> synonymes
> uniforme noir
> visible / accessible
> oui / oui
> états
> intact, opaque, transportable, dénombrable, caché, portable; sa description est, unique, disponible et présent.
> propriétés
> quantité : 1
> description : "[1ère fois]Un uniforme militaire noir, il semble que quelqu'un l'ait déjà fouillé.[si L’historique contient "passé:marine" ] il est étrange qu'aucun grade ou signe distinctif ne soit présent. Cela vous rappel les opérations spéciales.[finsi][puis]Un uniforme militaire noir[fin choix]" ; son aperçu est "[initialement]Il porte un uniforme noir[puis]Un uniforme noir[fin choix]."
> emplacement
> salle_1 (sur mort)

code 
```

PARTIE "01 - Informations sur le jeu".
  Le titre du jeu est "Un réveil difficile".
  L’auteur du jeu est "Aymeric Besset".
  La version du jeu est "0.01".
  Le titre de la licence est "Creative Commons Attribution 4.0 International License".
  Le lien de la licence est "https://creativecommons.org/licenses/by/4.0/".

PARTIE "02 - Mémoire du jeu".
  L’historique est une liste.
  Désactiver la description des objets supportés.
  Désactiver l'affichage des directions des sorties.

  -- ///////////////////////
  --   LE REVEIL
  -- ///////////////////////
PARTIE "03 - Jeu".
  CHAPITRE "01 - la salle du réveil".
    salle_1 est un lieu.
      Son titre est "Salle 01".
      Sa description est "Une grande salle avec des caissons à examiner".
        elle est éclairé.

    
    -- ///////////////////////
    --   LES OBJETS
    -- ///////////////////////
    SCÈNE "01-04 - les objets".
      -- ///////////////////////
      -- CAISSONS
      les caissons sont un objet décoratif dans salle_1. 
        sa description est "D'autres {-caissons d'hypersommeil-} semblent cassés, leurs occupants {-morts-}, et d'autres encore semblent déjà ouvert et vide. Un {-corps-} semble différent. Votre {-caisson-} porte le numéro 13.".
        --son aperçu est "Du {-texte-} clignote sur l'{-écran-}".
        Interpréter caisson, caisson d'hypersommeil, caissons d'hypersommeil, tube, tubes comme Les caissons.
        après examiner les caissons:
          changer le mort n'est plus invisible.
      
      -- Corps
      le mort est un support invisible dans salle_1.
        sa description est "[Initialement]Un {-corps-} est différent, il est par terre et ne semble pas être un occupant des {-caissons-}.
        [puis] Le corps qui n'est pas celui d'un prisonnier.[fin choix]".
        son aperçu est "[initialement]Un {-corps-} semble différent".
        il est fixé.
      Interpréter corps, morts, cadavre comme le mort.
    
      l'uniforme est un objet caché sur le mort.
          il est portable;
          sa description est "[1ère fois]Un uniforme militaire noir, il semble que quelqu'un l'ait déjà fouillé.[si L’historique contient "passé:marine"] il est étrange qu'aucun grade ou signe distinctif ne soit présent. Cela vous rappel les opérations spéciales.[finsi][puis]Un uniforme militaire noir[fin choix]";
          son aperçu est "[initialement]Il porte un {-uniforme noir-}[puis]Un uniforme noir[fin choix].".
          interpréter uniforme noir comme l'uniforme.
```
